"use client";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Providers } from "@/context/ThemeProvider";
import Header from "@/components/Header";
import { useEffect, useState } from "react";
import { AnimatePresence } from "framer-motion";
import LoadingScreen from "@/components/LoadingScreen";
import Sidebar from "@/components/Sidebar";

const lato = Lato({
  weight: ["300", "400", "700", "100", "100", "900"],
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLoading, setIsLoading] = useState(true);
  useEffect(() => {
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 200);

    return () => clearTimeout(timer);
  }, []);
  return (
    <html lang="en">
      <body className={lato.className}>
        {
          <Providers>
            <AnimatePresence>{isLoading && <LoadingScreen />}</AnimatePresence>
            {!isLoading && (
              <div className="bg-gradient-to-t from-white via-yellow-50 to-[#FEFBD8] dark:bg-gradient-to-r select-none overflow-x-hidden dark:from-[#17153B] dark:to-[#070F2B]">
                <Header />
                <div className="relative z-50">
                  <Sidebar />
                </div>
                {children}
              </div>
            )}
          </Providers>
        }
      </body>
    </html>
  );
}
