"use client";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Providers } from "@/context/ThemeProvider";
import Header from "@/components/Header";
import { useEffect, useState } from "react";
import { AnimatePresence } from "framer-motion";
import LoadingScreen from "@/components/LoadingScreen";

const lato = Lato({ weight: "300", subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLoading, setIsLoading] = useState(true);
  useEffect(() => {
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 200);

    return () => clearTimeout(timer);
  }, []);
  return (
    <html lang="en">
      <body className={lato.className}>
        {
          <Providers>
            <AnimatePresence>{isLoading && <LoadingScreen />}</AnimatePresence>
            {!isLoading && (
              <div className="dark:bg-gradient-to-r select-none overflow-x-hidden from-[#17153B] to-[#070F2B]">
                <Header />
                {children}
              </div>
            )}
          </Providers>
        }
      </body>
    </html>
  );
}
